#!/usr/bin/env python3
"""Generate native catalogs from localization/fr.json. No credentials or network access.

Legacy Java display strings use Translations at the presentation boundary; XML and
SwiftUI literals use normal platform resources. Run after updating the dictionary.
"""
from pathlib import Path
import hashlib, html, json, re
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape
ROOT = Path(__file__).resolve().parent.parent
translations = json.loads((ROOT / 'localization/fr.json').read_text())
def quoted(value): return json.dumps(value, ensure_ascii=False)
def xmltext(value): return escape(value).replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')
java = '''package dev.bennett.codexmeter;

import java.util.Locale;
import java.util.Map;

/** Generated by scripts/generate-localizations.py; edit localization/fr.json. */
public final class Translations {
    private Translations() { }
    private static final Map<String, String> FRENCH = Map.ofEntries(
'''
java += ',\n'.join('        Map.entry(' + quoted(en) + ', ' + quoted(fr) + ')' for en, fr in translations.items())
java += '''
    );
    public static String t(String value) {
        if (value == null || !Locale.getDefault().getLanguage().equals("fr")) return value;
        String exact = FRENCH.get(value);
        if (exact != null) return exact;
        String[][] prefixes = {{"View all models (", "Voir tous les modèles ("},
            {"Discovered ", "Découvert "}, {"Checked ", "Vérifié "}, {"Updated ", "Actualisé "},
            {"Resets ", "Réinitialisation "}, {"Automatic refresh every ", "Actualisation automatique toutes les "},
            {"The provider could not be refreshed (HTTP ", "Impossible d’actualiser le fournisseur (HTTP "}};
        for (String[] pair : prefixes) if (value.startsWith(pair[0])) return pair[1] + value.substring(pair[0].length());
        if (value.contains(" · ")) return String.join(" · ", labels(value.split(" · ")));
        return value;
    }
    public static CharSequence t(CharSequence value) { return value instanceof String ? t((String) value) : value; }
    public static int t(int resource) { return resource; }
    public static String[] labels(String[] values) {
        if (values == null) return null;
        String[] result = new String[values.length];
        for (int i = 0; i < values.length; i++) result[i] = t(values[i]);
        return result;
    }
}
'''
(ROOT / 'android/shared/src/main/java/dev/bennett/codexmeter/Translations.java').write_text(java)
missing = set()
for module in ['app', 'wear']:
    root = ROOT / f'android/{module}/src/main/res'
    generated = {}
    # Turn only display attributes into stable Android resource references.
    for folder in ['xml', 'layout']:
        for file in (root / folder).glob('*.xml'):
            source = file.read_text()
            def replace(match):
                value = html.unescape(match[2])
                if not re.search('[a-zA-Z]{3}', value): return match[0]
                name = 'localized_' + hashlib.sha1(value.encode()).hexdigest()[:12]
                generated[name] = value
                return match[1] + '"@string/' + name + '"'
            source = re.sub(r'(android:(?:text|title|summary|contentDescription|hint)=)"([^"@?][^"]*)"', replace, source)
            file.write_text(source)
    generated_file = root / 'values/localized_display.xml'
    if generated_file.exists():
        for item in ET.parse(generated_file).getroot(): generated.setdefault(item.attrib['name'], (item.text or '').replace("\\'", "'").replace('\\"', '"').replace('\\n', '\n'))
    generated_file.write_text('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n' + '\n'.join(
        '    <string name="' + key + '" formatted="false">' + xmltext(value) + '</string>' for key,value in sorted(generated.items())) + '\n</resources>\n')
    french = root / 'values-fr'; french.mkdir(exist_ok=True)
    for source in (root / 'values').glob('*.xml'):
        tree = ET.parse(source).getroot()
        items = []
        for element in tree:
            if element.tag not in ['string', 'string-array', 'plurals'] or element.attrib.get('translatable') == 'false': continue
            if element.tag == 'string-array' and not element.attrib['name'].endswith(('_entries', '_labels')): continue
            for item in [element] if element.tag == 'string' else list(element):
                value = (item.text or '').replace("\\'", "'").replace('\\"', '"')
                if value in translations: item.text = translations[value]
                elif re.search('[a-zA-Z]{3}', value) and not value.startswith(('@', 'http', 'dev.')): missing.add(value)
            items.append(element)
        if not items: continue
        output = '<resources>\n'
        for element in items:
            name = element.attrib['name']
            if element.tag == 'string': output += '    <string name="'+name+'"'+(' formatted="false"' if element.attrib.get('formatted') == 'false' else '')+'>'+xmltext(element.text or '')+'</string>\n'
            else:
                output += '    <'+element.tag+' name="'+name+'">\n'
                for item in element:
                    attrs = ''.join(' '+k+'="'+v+'"' for k,v in item.attrib.items())
                    output += '        <item'+attrs+'>'+xmltext(item.text or '')+'</item>\n'
                output += '    </'+element.tag+'>\n'
        (french / source.name).write_text('<?xml version="1.0" encoding="utf-8"?>\n'+output+'</resources>\n')
# Literal SwiftUI strings are localized by the environment locale and normal String Catalogs.
for target in ['CodexMeter','CodexMeterWidgets']:
    path = ROOT / f'ios/{target}/Localizable.xcstrings'
    catalog = json.loads(path.read_text())
    for en, fr in translations.items():
        item = catalog['strings'].setdefault(en, {})
        item.setdefault('localizations', {})['fr'] = {'stringUnit': {'state': 'translated', 'value': fr}}
    path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2)+'\n')
# Untranslated values are primarily brand names and are deliberately kept verbatim.
print(f'Generated {len(translations)} French translations; {len(missing)} Android source values need review.')
